-- Vol 1, Chapter 2: People and Organizations
-- Built up one figure at a time; each section is headed by the figure it implements.

-- ============================================================
-- Fig 2.3 (part 1, moved up) — Party supertype
-- ============================================================
-- Defined first because ORGANIZATION (2.1) and PERSON (2.2b) are its subtypes
-- and reference it. The rest of 2.3 (classification) is at the end of the file.
--
-- party_kind is not in the book: it is a discriminator that, together with the
-- composite foreign keys on the subtype tables, guarantees a party is a person
-- OR an organization, never both. (Nothing forces a party to have a subtype
-- row at all; that would need a deferred trigger.)

create table party (
  party_id   integer generated by default as identity primary key,
  party_kind text not null check (party_kind in ('PERSON', 'ORGANIZATION')),
  unique (party_id, party_kind)   -- target for the subtypes' composite FKs
);

-- ============================================================
-- Fig 2.1 — Organization (subtype of PARTY since 2.3)
-- ============================================================
-- The book draws a subtype hierarchy where only LEGAL ORGANIZATION carries an
-- attribute. The other subtypes are pure classifications, so instead of six
-- attribute-less tables they become rows in a self-referencing type table.
-- (See NOTES.md, "Design decisions".)

create table organization_type (
  organization_type_id text primary key,
  parent_type_id       text references organization_type,
  description          text not null
);

create table organization (
  party_id             integer primary key,
  party_kind           text not null default 'ORGANIZATION' check (party_kind = 'ORGANIZATION'),
  organization_type_id text not null references organization_type,
  name                 text not null,
  -- Only meaningful for LEGAL subtypes; not enforced (see NOTES.md).
  federal_tax_id_num   text,
  foreign key (party_id, party_kind) references party (party_id, party_kind)
);

-- ============================================================
-- Fig 2.2a — Person (flat)
-- ============================================================
-- Kept as person_flat (2.2b below takes the name "person") so both models can
-- be queried side by side. Standalone: it is NOT a party subtype.
-- One row per person; everything optional; "current_*" columns can only hold
-- the present value, so every change overwrites history.

create table person_flat (
  person_id                    integer generated by default as identity primary key,
  current_last_name            text,
  current_first_name           text,
  current_middle_name          text,
  current_personal_title       text,
  current_suffix               text,
  current_nickname             text,
  gender                       text,      -- free text: nothing stops 'F' vs 'Female'
  birth_date                   date,
  height                       numeric,   -- unit? cm or inches: the column can't say
  weight                       numeric,
  mothers_maiden_name          text,
  marital_status               text,
  social_security_no           text,
  current_passport_no          text,      -- one passport only: dual citizens lose one
  current_passport_expire_date date,
  total_years_work_experience  integer,
  comment                      text
);

-- ============================================================
-- Fig 2.2b — Person, alternate model (subtype of PARTY since 2.3)
-- ============================================================
-- The volatile attributes of 2.2a move into their own entities with
-- from/thru dates (history) and *_type lookups (controlled values).

create table gender_type (
  gender_type_id text primary key,
  description    text not null
);

create table person (
  party_id                    integer primary key,
  party_kind                  text not null default 'PERSON' check (party_kind = 'PERSON'),
  gender_type_id              text not null references gender_type,   -- solid line: every person must have one
  birth_date                  date,
  mothers_maiden_name         text,
  social_security_no          text,
  total_years_work_experience integer,
  comment                     text,
  foreign key (party_id, party_kind) references party (party_id, party_kind)
);

-- Names -------------------------------------------------------
-- Fig 2.3 makes current first and last name mandatory. With names as rows
-- that can't be declared; queries.sql has a data-quality check instead.

create table person_name_type (
  person_name_type_id text primary key,
  description         text not null
);

create table person_name (
  party_id            integer not null references person,
  name_seq_id         integer not null,
  person_name_type_id text    not null references person_name_type,
  from_date           date    not null,
  thru_date           date,
  name                text    not null,
  primary key (party_id, name_seq_id),
  check (thru_date is null or thru_date > from_date)
);

-- Marital status ----------------------------------------------

create table marital_status_type (
  marital_status_type_id text primary key,
  description            text not null
);

create table marital_status (
  party_id               integer not null references person,
  marital_status_type_id text    not null references marital_status_type,
  from_date              date    not null,
  thru_date              date,
  primary key (party_id, marital_status_type_id, from_date),
  check (thru_date is null or thru_date > from_date)
);

-- Physical characteristics ------------------------------------

create table physical_characteristic_type (
  physical_characteristic_type_id text primary key,
  description                     text not null   -- the unit lives here, e.g. 'Height (cm)'
);

create table physical_characteristic (
  party_id                        integer not null references person,
  physical_characteristic_type_id text    not null references physical_characteristic_type,
  from_date                       date    not null,
  thru_date                       date,
  value                           text,           -- one column for every characteristic: can't be type-checked
  -- DEVIATION: the book marks from_date as * (not part of the identifier),
  -- which would allow only one value per person and type, ever. Including it
  -- in the key lets a weight change over time. See NOTES.md.
  primary key (party_id, physical_characteristic_type_id, from_date),
  check (thru_date is null or thru_date > from_date)
);

-- Citizenship and passports -----------------------------------

create table country (
  country_id text primary key,   -- ISO 3166 alpha-2
  name       text not null       -- not drawn in the book; added so rows are readable
);

create table citizenship (
  party_id   integer not null references person,
  country_id text    not null references country,
  from_date  date    not null,
  thru_date  date,
  primary key (party_id, country_id, from_date),
  check (thru_date is null or thru_date > from_date)
);

-- A passport hangs off a citizenship, so it inherits that relationship's
-- three-part key as a composite foreign key.
create table passport (
  passport_id           integer generated by default as identity primary key,
  party_id              integer not null,
  country_id            text    not null,
  citizenship_from_date date    not null,
  passport_num          text    not null,
  issue_date            date    not null,
  expiration_date       date    not null,
  foreign key (party_id, country_id, citizenship_from_date)
    references citizenship (party_id, country_id, from_date),
  unique (country_id, passport_num),
  check (expiration_date > issue_date)
);

-- ============================================================
-- Fig 2.3 (part 2) — Party classification
-- ============================================================
-- Subtype = what a party IS (fixed, exactly one). Classification = how we
-- categorise it (many, dated, just data). The classification subtypes in the
-- book (organization: minority/industry/size; person: EEOC/income) have no
-- attributes, so they become a three-level party_type hierarchy:
--   ORGANIZATION_CLASSIFICATION > INDUSTRY > IND_LOGISTICS
--
-- applies_to_kind + the composite FKs below make the database reject, e.g.,
-- an INDUSTRY classification on a person.

create table party_type (
  party_type_id   text primary key,
  parent_type_id  text references party_type,
  applies_to_kind text not null check (applies_to_kind in ('PERSON', 'ORGANIZATION')),
  description     text not null,
  unique (party_type_id, applies_to_kind)
);

create table party_classification (
  party_id      integer not null,
  party_type_id text    not null,
  party_kind    text    not null,
  from_date     date    not null,
  thru_date     date,
  primary key (party_id, party_type_id, from_date),
  foreign key (party_id, party_kind)      references party (party_id, party_kind),
  foreign key (party_type_id, party_kind) references party_type (party_type_id, applies_to_kind),
  check (thru_date is null or thru_date > from_date)
);

-- Current display name for any party (person or organization). Later chapters
-- will want "the name of party X" constantly; this is where the supertype pays off.
create view party_display_name as
select p.party_id,
       p.party_kind,
       coalesce(
         o.name,
         concat_ws(' ',
           max(n.name) filter (where n.person_name_type_id = 'FIRST'),
           max(n.name) filter (where n.person_name_type_id = 'LAST'))
       ) as name
from party p
left join organization o on o.party_id = p.party_id
left join person_name n  on n.party_id = p.party_id and n.thru_date is null
group by p.party_id, p.party_kind, o.name;

-- ============================================================
-- Fig 2.4 — Party roles
-- ============================================================
-- A role is something a party *plays* (customer, supplier, employee), not
-- something it *is*. One party can hold many roles, each dated.
--
-- ROLE TYPE is drawn as a supertype whose only subtype so far is PARTY ROLE
-- TYPE; other role kinds come later, so for now there is a single role_type
-- table (refactor if/when another subtype appears). The book's role subtypes
-- (PERSON ROLE > EMPLOYEE, ORGANIZATION ROLE > DISTRIBUTION CHANNEL > AGENT, …)
-- become a role_type hierarchy.

create table role_type (
  role_type_id   text primary key,
  parent_type_id text references role_type,
  description    text not null
);

-- Which kind of party may play which role. A role either kind can play
-- (CUSTOMER, PROSPECT, SHAREHOLDER) gets two rows. Grouping types
-- (PERSON_ROLE, CUSTOMER, DISTRIBUTION_CHANNEL…) get none, so only concrete
-- roles can be assigned.
create table role_type_party_kind (
  role_type_id text not null references role_type,
  party_kind   text not null check (party_kind in ('PERSON', 'ORGANIZATION')),
  primary key (role_type_id, party_kind)
);

create table party_role (
  party_role_id integer generated by default as identity primary key,
  party_id      integer not null,
  party_kind    text    not null,
  role_type_id  text    not null,
  from_date     date    not null,   -- * in the book: mandatory, but not part of the identifier
  thru_date     date,
  -- The book's identifier is (party, party_role_id). party_role_id is already
  -- unique on its own, so it stays the PK; this pair lets child tables
  -- reference "role X of party Y" and have both checked.
  unique (party_id, party_role_id),
  foreign key (party_id, party_kind)     references party (party_id, party_kind),
  foreign key (role_type_id, party_kind) references role_type_party_kind (role_type_id, party_kind),
  check (thru_date is null or thru_date > from_date)
);
