-- Vol 1, Chapter 2: People and Organizations
-- Built up one figure at a time; each section is headed by the figure it implements.

-- ============================================================
-- Fig 2.1 — Organization
-- ============================================================
-- The book draws a subtype hierarchy where only LEGAL ORGANIZATION carries an
-- attribute. The other subtypes are pure classifications, so instead of six
-- attribute-less tables they become rows in a self-referencing type table.
-- (See NOTES.md, "Design decisions".)

create table organization_type (
  organization_type_id text primary key,
  parent_type_id       text references organization_type,
  description          text not null
);

create table organization (
  organization_id      integer generated by default as identity primary key,
  organization_type_id text not null references organization_type,
  name                 text not null,
  -- Only meaningful for LEGAL subtypes; not enforced (see NOTES.md).
  federal_tax_id_num   text
);

-- ============================================================
-- Fig 2.2a — Person (flat)
-- ============================================================
-- Kept as person_flat (2.2b below takes the name "person") so both models can
-- be queried side by side.
-- One row per person; everything optional; "current_*" columns can only hold
-- the present value, so every change overwrites history.

create table person_flat (
  person_id                    integer generated by default as identity primary key,
  current_last_name            text,
  current_first_name           text,
  current_middle_name          text,
  current_personal_title       text,
  current_suffix               text,
  current_nickname             text,
  gender                       text,      -- free text: nothing stops 'F' vs 'Female'
  birth_date                   date,
  height                       numeric,   -- unit? cm or inches: the column can't say
  weight                       numeric,
  mothers_maiden_name          text,
  marital_status               text,
  social_security_no           text,
  current_passport_no          text,      -- one passport only: dual citizens lose one
  current_passport_expire_date date,
  total_years_work_experience  integer,
  comment                      text
);

-- ============================================================
-- Fig 2.2b — Person, alternate model
-- ============================================================
-- The volatile attributes of 2.2a move into their own entities with
-- from/thru dates (history) and *_type lookups (controlled values).

create table gender_type (
  gender_type_id text primary key,
  description    text not null
);

create table person (
  person_id                   integer generated by default as identity primary key,
  gender_type_id              text not null references gender_type,   -- solid line: every person must have one
  birth_date                  date,
  mothers_maiden_name         text,
  social_security_no          text,
  total_years_work_experience integer,
  comment                     text
);

-- Names -------------------------------------------------------

create table person_name_type (
  person_name_type_id text primary key,
  description         text not null
);

create table person_name (
  person_id           integer not null references person,
  name_seq_id         integer not null,
  person_name_type_id text    not null references person_name_type,
  from_date           date    not null,
  thru_date           date,
  name                text    not null,
  primary key (person_id, name_seq_id),
  check (thru_date is null or thru_date > from_date)
);

-- Marital status ----------------------------------------------

create table marital_status_type (
  marital_status_type_id text primary key,
  description            text not null
);

create table marital_status (
  person_id              integer not null references person,
  marital_status_type_id text    not null references marital_status_type,
  from_date              date    not null,
  thru_date              date,
  primary key (person_id, marital_status_type_id, from_date),
  check (thru_date is null or thru_date > from_date)
);

-- Physical characteristics ------------------------------------

create table physical_characteristic_type (
  physical_characteristic_type_id text primary key,
  description                     text not null   -- the unit lives here, e.g. 'Height (cm)'
);

create table physical_characteristic (
  person_id                       integer not null references person,
  physical_characteristic_type_id text    not null references physical_characteristic_type,
  from_date                       date    not null,
  thru_date                       date,
  value                           text,           -- one column for every characteristic: can't be type-checked
  -- DEVIATION: the book marks from_date as * (not part of the identifier),
  -- which would allow only one value per person and type, ever. Including it
  -- in the key lets a weight change over time. See NOTES.md.
  primary key (person_id, physical_characteristic_type_id, from_date),
  check (thru_date is null or thru_date > from_date)
);

-- Citizenship and passports -----------------------------------

create table country (
  country_id text primary key,   -- ISO 3166 alpha-2
  name       text not null       -- not drawn in the book; added so rows are readable
);

create table citizenship (
  person_id  integer not null references person,
  country_id text    not null references country,
  from_date  date    not null,
  thru_date  date,
  primary key (person_id, country_id, from_date),
  check (thru_date is null or thru_date > from_date)
);

-- A passport hangs off a citizenship, so it inherits that relationship's
-- three-part key as a composite foreign key.
create table passport (
  passport_id           integer generated by default as identity primary key,
  person_id             integer not null,
  country_id            text    not null,
  citizenship_from_date date    not null,
  passport_num          text    not null,
  issue_date            date    not null,
  expiration_date       date    not null,
  foreign key (person_id, country_id, citizenship_from_date)
    references citizenship (person_id, country_id, from_date),
  unique (country_id, passport_num),
  check (expiration_date > issue_date)
);
