-- Vol 1, Chapter 3: Products
-- Built up one figure at a time; each section is headed by the figure it implements.
--
-- Key style (as in Ch 2): every table has a single-column primary key
-- (surrogate integer, or a text code for lookups) and plain foreign keys.
-- Rules a plain FK can't express are data-quality queries in queries.sql.

-- ============================================================
-- Fig 3.1 — Product definition
-- ============================================================
-- A PRODUCT is something the enterprise offers, independent of who supplies
-- it or how many we have on the shelf (those come later in the chapter).
--
-- GOOD and SERVICE are exclusive subtypes with no attributes of their own, so
-- they become a product_kind discriminator instead of two empty tables (same
-- move as party_kind in Ch 2).
--
-- The book's sample ids (PAP192, CNS109) are readable codes. We keep a
-- surrogate product_id; those codes are identifiers and get a home in Fig 3.3.
--
-- The three dates are milestones, not an effectivity period. Like thru_date,
-- the discontinuation dates are exclusive: the first day the product is no
-- longer sold / supported. A data-quality query checks their order.

create table product (
  product_id                   integer generated by default as identity primary key,
  product_kind                 text not null check (product_kind in ('GOOD', 'SERVICE')),
  name                         text not null,
  introduction_date            date,
  sales_discontinuation_date   date,
  support_discontinuation_date date,
  comment                      text
);
