-- Vol 1, Chapter 3: Products
-- Built up one figure at a time; each section is headed by the figure it implements.
--
-- Key style (as in Ch 2): every table has a single-column primary key
-- (surrogate integer, or a text code for lookups) and plain foreign keys.
-- Rules a plain FK can't express are data-quality queries in queries.sql.

-- ============================================================
-- Fig 3.1 — Product definition
-- ============================================================
-- A PRODUCT is something the enterprise offers, independent of who supplies
-- it or how many we have on the shelf (those come later in the chapter).
--
-- GOOD and SERVICE are exclusive subtypes with no attributes of their own, so
-- they become a product_kind discriminator instead of two empty tables (same
-- move as party_kind in Ch 2).
--
-- The book's sample ids (PAP192, CNS109) are readable codes. We keep a
-- surrogate product_id; those codes are identifiers and get a home in Fig 3.3.
--
-- The three dates are milestones, not an effectivity period. Like thru_date,
-- the discontinuation dates are exclusive: the first day the product is no
-- longer sold / supported. A data-quality query checks their order.

create table product (
  product_id                   integer generated by default as identity primary key,
  product_kind                 text not null check (product_kind in ('GOOD', 'SERVICE')),
  name                         text not null,
  introduction_date            date,
  sales_discontinuation_date   date,
  support_discontinuation_date date,
  comment                      text
);

-- ============================================================
-- Fig 3.2 — Product category
-- ============================================================
-- Categories are data, not columns: a product can sit in many categories,
-- each period dated, and one of them is flagged primary.
--
-- The PRODUCT CATEGORY subtypes (usage, industry, materials) have no
-- attributes, so they become rows in product_category_type: the "dimension"
-- a category belongs to.
--
-- PRODUCT CATEGORY ROLLUP is many-to-many, so a category can have several
-- parents (Business forms sits under Paper and under Printed materials). The
-- figure shows no dates on the rollup, so there are none here.

create table product_category_type (
  product_category_type_id text primary key,
  description              text not null
);

create table product_category (
  product_category_id      integer generated by default as identity primary key,
  product_category_type_id text not null references product_category_type,
  description              text not null
);

create table product_category_rollup (
  product_category_rollup_id  integer generated by default as identity primary key,
  parent_product_category_id  integer not null references product_category,   -- "made up of"
  child_product_category_id   integer not null references product_category,   -- "part of" / "within"
  check (parent_product_category_id <> child_product_category_id)
);

-- primary_flag: at most one current primary category per product is a rule a
-- plain FK can't hold; a data-quality query checks it.
create table product_category_classification (
  product_category_classification_id integer generated by default as identity primary key,
  product_id                         integer not null references product,
  product_category_id                integer not null references product_category,
  from_date                          date    not null,
  thru_date                          date,
  primary_flag                       boolean not null default false,
  comment                            text,
  check (thru_date is null or thru_date > from_date)
);

-- MARKET INTEREST: which kinds of party (Ch 2's party_type, e.g. an industry
-- or a size band) are interested in which product categories. Knowledge about
-- markets, not about any one customer.
create table market_interest (
  market_interest_id  integer generated by default as identity primary key,
  product_category_id integer not null references product_category,
  party_type_id       text    not null references party_type,
  from_date           date    not null,
  thru_date           date,
  check (thru_date is null or thru_date > from_date)
);

-- Every category paired with each of its ancestors at any depth (the category
-- itself is NOT included). UNION, not UNION ALL, so a cycle in the rollup data
-- stops the walk instead of looping forever; a data-quality query reports it.
create view product_category_ancestor as
with recursive walk (product_category_id, ancestor_id) as (
  select child_product_category_id, parent_product_category_id
  from product_category_rollup
  union
  select w.product_category_id, r.parent_product_category_id
  from walk w
  join product_category_rollup r on r.child_product_category_id = w.ancestor_id
)
select product_category_id, ancestor_id from walk;

-- ============================================================
-- Fig 3.3 — Product identification
-- ============================================================
-- A product can carry many codes: our SKU, the manufacturer's part number, a
-- UPC barcode, an ISBN. Each is a row (type + value), not a column per code.
--
-- The GOOD IDENTIFICATION subtypes (SKU, UPCA, UPCE, ISBN, …) have no
-- attributes, so they are rows in the book's own IDENTIFICATION TYPE table.
-- The book names the entity GOOD identification but links it to PRODUCT, so
-- product_id it is (see NOTES for the open question).
--
-- value_pattern is not in the book: a regular expression the codes of that
-- type must match (null = free format). A rule stored as data, checked by a
-- data-quality query.

create table identification_type (
  identification_type_id text primary key,
  description            text not null,
  value_pattern          text
);

-- The book identifies a row by (product, identification type): one value per
-- type per product. We use a surrogate key; data-quality queries check that
-- rule and that no two products share the same code.
create table good_identification (
  good_identification_id integer generated by default as identity primary key,
  product_id             integer not null references product,
  identification_type_id text    not null references identification_type,
  id_value               text    not null
);

-- ============================================================
-- Fig 3.4 — Product feature
-- ============================================================
-- Features are characteristics or options a product can have (colour, size,
-- brand, a duplex unit, hourly billing). One feature is defined once and
-- reused across products; PRODUCT FEATURE APPLICABILITY says, per product and
-- period, whether it's required, standard, optional or selectable.

-- Units of measure come first: products and dimension features use them.
create table unit_of_measure (
  uom_id       text primary key,
  abbreviation text not null,
  description  text not null
);

-- One row = "1 from-unit equals conversion_factor to-units" (1 REAM = 500 EA).
-- The figure has no identifier of its own beyond the two units; a
-- data-quality query checks that a pair and its reverse agree.
create table unit_of_measure_conversion (
  unit_of_measure_conversion_id integer generated by default as identity primary key,
  from_uom_id                   text    not null references unit_of_measure,   -- "converted from"
  to_uom_id                     text    not null references unit_of_measure,   -- "converted into"
  conversion_factor             numeric not null check (conversion_factor > 0),
  check (from_uom_id <> to_uom_id)
);

-- PRODUCT "measured using" UNIT OF MEASURE: the unit a product is sold and
-- counted in (a ream, a box, an hour). Added to the 3.1 table here, where the
-- book introduces it. Optional (to check against the book).
alter table product
  add column uom_id text references unit_of_measure;

create table product_feature_category (
  product_feature_category_id integer generated by default as identity primary key,
  description                 text not null
);

-- The PRODUCT FEATURE subtypes become rows. Only DIMENSION has an attribute
-- (number_specified); it lives on product_feature as a nullable column, as
-- federal_tax_id_num did on organization in Ch 2, with a data-quality query.
create table product_feature_type (
  product_feature_type_id text primary key,
  description             text not null
);

create table product_feature (
  product_feature_id          integer generated by default as identity primary key,
  product_feature_type_id     text    not null references product_feature_type,
  product_feature_category_id integer references product_feature_category,   -- "categorized by"
  description                 text    not null,
  number_specified            numeric,                                        -- DIMENSION only
  uom_id                      text    references unit_of_measure              -- "measured using"
);

-- REQUIRED / STANDARD / OPTIONAL / SELECTABLE: exclusive, no attributes,
-- so rows in a type table.
create table product_feature_applicability_type (
  product_feature_applicability_type_id text primary key,
  description                           text not null
);

create table product_feature_applicability (
  product_feature_applicability_id      integer generated by default as identity primary key,
  product_id                            integer not null references product,
  product_feature_id                    integer not null references product_feature,
  product_feature_applicability_type_id text    not null references product_feature_applicability_type,
  from_date                             date    not null,
  thru_date                             date,
  check (thru_date is null or thru_date > from_date)
);

create table product_feature_interaction_type (
  product_feature_interaction_type_id text primary key,
  description                         text not null
);

-- Read a DEPENDENCY as "choosing product_feature_id needs factor_product_feature_id";
-- an INCOMPATIBILITY as "these two can't be chosen together" (either order).
-- product_id is the context: null = the interaction holds for every product.
create table product_feature_interaction (
  product_feature_interaction_id      integer generated by default as identity primary key,
  product_feature_interaction_type_id text    not null references product_feature_interaction_type,
  product_feature_id                  integer not null references product_feature,   -- "of" / "selected in"
  factor_product_feature_id           integer not null references product_feature,   -- "a factor in"
  product_id                          integer references product,                    -- "applicable within the context of"
  check (product_feature_id <> factor_product_feature_id)
);
